# Generated by Django 4.1.4 on 2022-12-09 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_purchase_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='Menu',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 9, 22, 41, 59, 946779)),
        ),
    ]
