# Generated by Django 4.1.4 on 2022-12-09 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_menu_price_alter_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 9, 23, 6, 4, 473517)),
        ),
    ]
