# Generated by Django 4.1.4 on 2022-12-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_ingredient_reciperequirement_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
